"""Core data types for the Sentinel proactivity subsystem."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Literal

Action = Literal[
    "skip",  # nothing worth doing this tick
    "nudge",  # send a standalone message NOW
    "nudge_inject",  # append to agent's next reply in target_session
    # (use when user is mid-conversation and our info is
    # naturally additive to what agent is about to say)
    "nudge_defer",  # wait until target_session's current thread settles,
    # then send as a follow-up (use when user is mid-task
    # and interrupting would hurt, but we still have value
    # to deliver after)
    "spawn_agent",  # dispatch a micro-agent for a multi-step task
]
Priority = Literal["low", "medium", "high"]
RoutineStatus = Literal["candidate", "active", "paused", "retired"]


@dataclass(frozen=True)
class LLMValidation:
    """LLM verdict on whether a learned routine is a real recurring habit
    vs a keyword-coincidence in the user's history.

    Attached to ``Routine`` after Stage 1 (RoutineValidator) runs; persisted
    in routine_store so we don't re-call the LLM on every Planner tick.
    """

    is_routine: bool
    confidence: float  # 0-1
    reason: str
    validated_at_ms: int


@dataclass
class Routine:
    """A detected recurring user behavior pattern.

    ``weight`` is a recency-decayed occurrence sum (set by
    ``RoutineLearner.learn_with_decay``; defaults to ``occurrence_count``
    on plain-frequency callers). ``description`` is an optional
    human-friendly one-liner generated by ``RoutineAggregator``;
    ``semantic_group`` is its cluster key (e.g. "morning_standup_family")
    so two near-duplicate routines can be collapsed in the menu.

    ``llm_validation`` is the cached output of RoutineValidator (Stage 1).
    None means "not yet validated"; once set, downstream surfacing can use
    ``is_routine`` + ``confidence`` to gate promotion to active.
    """

    id: str
    pattern: str  # e.g. "post to Xiaohongshu every Tuesday"
    keywords: list[str] = field(default_factory=list)
    day_of_week: int | None = None  # 0=Monday, None=every day
    time_slot: tuple[int, int] | None = None  # (start_hour, end_hour)
    status: RoutineStatus = "candidate"
    occurrence_count: int = 0
    last_triggered: str | None = None
    user_confirmed: bool = False
    weight: float = 0.0
    description: str | None = None
    semantic_group: str | None = None
    user_confirmed_at_ms: int | None = None
    dismissed_at_ms: int | None = None
    llm_validation: LLMValidation | None = None


@dataclass
class ActiveSession:
    """A minimal view of an active channel session."""

    key: str  # e.g. "cli:direct", "telegram:home"
    last_active_at: datetime
    last_user_message: str | None = None
    last_assistant_message: str | None = None
    status: str | None = None  # free-form hint like "waiting_for_response"


@dataclass
class NudgePolicyState:
    """Current state of the NudgePolicy (for prompt context)."""

    nudges_used_this_hour: int = 0
    in_quiet_hours: bool = False
    remaining_today: int = 10
    # Adaptive tuning multiplier (<= 1.0). Indicates how much NudgePolicy has
    # tightened the hour quota based on recent acceptance rate. Planner uses
    # this as a soft signal — when < 1.0, user has been dismissing nudges,
    # so raise the bar for what's worth sending.
    hour_quota_multiplier: float = 1.0


@dataclass
class PlannerContext:
    """All state a ProactivePlanner tick operates on.

    The production SentinelRunner will assemble this from MemoryStore /
    SessionManager / RoutineLearner / NudgePolicy. The eval harness
    assembles it from YAML fixtures. Either way, Planner only sees this.
    """

    now: datetime
    memory_md: str = ""
    history_md_recent: str = ""
    active_sessions: list[ActiveSession] = field(default_factory=list)
    routines: list[Routine] = field(default_factory=list)
    calendar: list[str] = field(default_factory=list)
    nudge_policy_state: NudgePolicyState = field(default_factory=NudgePolicyState)
    last_decision: "PlannerDecision | None" = None
    user_profile: str = ""
    # Recent fire history (v10+): lets Planner see what topics it has
    # already pushed and whether the user dismissed them. Format:
    #   {"recent_fires": [{ts, topic_tag, message_preview}, ...],
    #    "topic_counts_24h": {tag: n, ...},
    #    "topic_counts_7d":  {tag: n, ...},
    #    "recent_dismissals": [{ts, session_key, reason}, ...]}
    fire_history: dict = field(default_factory=dict)
    # Selected attention.md sections — sentinel/cron-derived state for
    # decision-relevant signals (Pending proposals, Recent stance log,
    # Predicted next 3 days, etc.). Section selection lives in
    # SentinelConfig.attention_planner_sections.
    attention_md: str = ""
    # Folded single-line view of behaviors.md tail within
    # behaviors_planner_window_days. One line per event:
    #   "- [MM-DD HH:MM-HH:MM Nt] intent→outcome topic #project: summary"
    behaviors_recent: str = ""


@dataclass
class PlannerDecision:
    """Structured output from a Planner tick."""

    action: Action
    reason: str = ""
    priority: Priority = "low"
    proactivity_score: float = 0.0  # 0-1, per §1.2 finding 3 / ContextAgent
    target_session: str | None = None
    nudge_message: str | None = None  # required when action in {nudge, nudge_inject, nudge_defer}
    spawn_task: str | None = None  # required when action=spawn_agent
    defer_condition: str | None = None  # required when action=nudge_defer;
    # natural-language wait condition
    # (e.g. "user's back-pain consultation thread ends")
    topic_tag: str | None = None  # short stable topic key for per-topic
    # hour quota in NudgePolicy. Examples:
    # "deadline_clawtrack", "birthday_xiaotang".
    # None = exempt from topic gate.
    raw_llm_response: dict[str, Any] | None = None  # debugging


ExecKind = Literal[
    "reply",  # inject a user-side prompt for the agent to handle
    "tool",  # invoke a tool from the agent's registry directly
    "spawn",  # SubagentManager.spawn(...)
    "routine_confirm",  # upgrade a candidate Routine to active + optional cron
]
TaskOptionType = Literal["routine_confirm", "ad_hoc"]


@dataclass
class TaskOption:
    """One actionable option presented to the user in a discovery menu.

    A TaskDiscoverer run produces 3-4 of these and bundles them into a
    PendingDecision; the menu is rendered as numbered markdown for the
    user to pick from. ``id`` is the stable handle the user's reply gets
    routed back to.
    """

    id: str  # "opt_<8hex>"
    title: str  # short user-facing title
    why: str  # 1-line rationale
    type: TaskOptionType  # routine_confirm | ad_hoc
    exec_kind: ExecKind
    exec_payload: dict[str, Any] = field(default_factory=dict)
    source: Literal["history", "memory", "routine"] = "history"
    priority: Priority = "medium"
    created_at_ms: int = 0
    deadline: str = ""  # ISO date, "" if none


@dataclass
class PendingDecision:
    """A discovery menu the user has been asked to pick from.

    Persisted to ``~/.raven/sentinel/pending_decisions.json`` until the
    user replies (consumed) or the TTL expires. One active decision per
    (channel, to) pair — a fresh discovery run on the same address
    supersedes the old one.

    Lifecycle (when ``require_confirm=True``):

        CREATED → consumed=False, awaiting_confirm=False, picked=None
            ↓ user picks option N
        AWAITING_CONFIRM → consumed=False, awaiting_confirm=True,
                           picked_option_id=opt_X
            ↓ user replies "yes"
        CONSUMED_OK → consumed=True, awaiting_confirm=False,
                      picked_option_id=opt_X (executor then runs)
            (or "no" → consumed=True, picked_option_id=None)

    Without confirm (require_confirm=False) the AWAITING_CONFIRM stop is
    skipped and pick → execute happens in one step.
    """

    decision_id: str  # "dec_<8hex>"
    channel: str
    to: str
    created_at_ms: int
    ttl_min: int = 60
    options: list[TaskOption] = field(default_factory=list)
    consumed: bool = False
    picked_option_id: str | None = None
    consumed_at_ms: int | None = None
    # Two-step confirm flow (set when require_confirm=True and user has
    # picked but not yet confirmed). While awaiting_confirm, the router
    # parses yes/no instead of new picks — see DecisionRouter.confirm_mode.
    awaiting_confirm: bool = False
    picked_at_ms: int | None = None

    def is_expired(self, now_ms: int) -> bool:
        return now_ms >= self.created_at_ms + self.ttl_min * 60_000


@dataclass
class RouteResult:
    """Outcome of DecisionRouter.maybe_consume() against an inbound user
    message. ``consumed=False`` means the message did not match a pending
    decision; AgentLoop should process it as normal user input.

    When the matched decision is in ``awaiting_confirm`` state, the
    router parses yes/no instead of a fresh pick and ``confirm_intent``
    carries the verdict. ``option`` is also populated in that case
    (set to the option the user originally picked, hydrated from
    ``pending.picked_option_id``) so the consumer can pass it
    straight to ActionExecutor without a second store lookup.
    """

    consumed: bool
    pending_decision_id: str | None = None
    option: TaskOption | None = None
    confidence: float = 0.0  # /pick N regex hit = 1.0; LLM = [0, 1]
    raw_match_method: Literal[
        "regex_pick",
        "regex_yesno",
        "llm_classifier",
        "none",
    ] = "none"
    # Only set when the matched decision was awaiting_confirm. None for
    # first-leg pick / skip flows.
    confirm_intent: Literal["confirm", "cancel"] | None = None


@dataclass
class ActionExecutionResult:
    """Final output of ActionExecutor.execute(option). ``side_effects``
    accumulates audit-grade messages (e.g. 'created cron job xxx',
    'upgraded routine yyy to active') for telemetry + user-facing log.

    Distinct from ``raven.proactive_engine.sentinel.executor.dispatcher.ExecutionResult``
    which carries the nudge-delivery outcome shape — ActionExecutor is
    for menu-pick execution."""

    status: Literal["ok", "deferred", "error"]
    exec_kind: ExecKind
    output_text: str | None = None
    side_effects: list[str] = field(default_factory=list)
    error: str | None = None
    elapsed_ms: int = 0


__all__ = [
    "Action",
    "ActionExecutionResult",
    "ActiveSession",
    "ExecKind",
    "LLMValidation",
    "NudgePolicyState",
    "PendingDecision",
    "PlannerContext",
    "PlannerDecision",
    "Priority",
    "Routine",
    "RoutineStatus",
    "RouteResult",
    "TaskOption",
    "TaskOptionType",
]
